# Generated by Django 2.0.6 on 2018-06-14 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('apellido', models.CharField(max_length=240)),
                ('rut', models.CharField(max_length=240)),
                ('mail', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('nombre', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Pasteles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('sabor', models.CharField(choices=[('Choc', 'Chocolate'), ('Mnj', 'Manjar'), ('Ntl', 'Nutella'), ('S.N', 'Selva negra'), ('C.P', 'Crema-Pastelera'), ('3L', '3Leches'), ('M.L', 'Merengue/Lucuma')], default='S.N', max_length=10)),
                ('tipo', models.CharField(choices=[('M.H', 'Millhojas'), ('Bzch', 'Bizcocho'), ('Ygt', 'Yogurt'), ('Pqq', 'Panqueque'), ('H.ca', 'Hojarasca'), ('Hlds', 'Heladas'), ('Mrg', 'Merengue')], default='Bzch', max_length=10)),
                ('vegano', models.BooleanField(default=False)),
                ('celiaco', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(default=datetime.date.today)),
                ('fecha_entrega', models.DateField()),
                ('sabor', models.CharField(choices=[('Choc', 'Chocolate'), ('Mnj', 'Manjar'), ('Ntl', 'Nutella'), ('S.N', 'Selva negra'), ('C.P', 'Crema-Pastelera'), ('3L', '3Leches'), ('M.L', 'Merengue/Lucuma')], default='S.N', max_length=10)),
                ('tipo', models.CharField(choices=[('M.H', 'Millhojas'), ('Bzch', 'Bizcocho'), ('Ygt', 'Yogurt'), ('Pqq', 'Panqueque'), ('H.ca', 'Hojarasca'), ('Hlds', 'Heladas'), ('Mrg', 'Merengue')], default='Bzch', max_length=10)),
                ('vegano', models.BooleanField(default=False)),
                ('celiaco', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('materia', models.ManyToManyField(blank=True, to='core.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(choices=[('Gr', 'Gramos'), ('Cc', 'Centimetro cubico')], default='Gr', max_length=12)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='stock',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Stock'),
        ),
    ]
