# Generated by Django 2.0.6 on 2018-06-21 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePastel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CantReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(choices=[('GR', 'Gramos'), ('CC', 'Centimetro cubico')], default='GR', max_length=2)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CapaPastel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crema', models.CharField(choices=[('CC', 'Crema de chocolate'), ('CB', 'Crema batida'), ('NL', 'Nutella'), ('MJ', 'Manjar'), ('CP', 'Crema Pastelera'), ('CM', 'Crema de Mantequilla'), ('ME', 'Merengue')], default='CB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('MP', 'Materia Prima'), ('IT', 'Ingrediente de Torta')], default='MP', max_length=2)),
                ('nombre', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('vegano', models.BooleanField(default=False)),
                ('celiaco', models.BooleanField(default=False)),
                ('base', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BasePastel')),
                ('capas', models.ManyToManyField(blank=True, related_name='capas_pastel', to='core.CapaPastel')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VE', 'Vendedor'), ('CL', 'Cliente'), ('AD', 'Administrador')], default='VE', max_length=2)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(default='', max_length=1)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='materia',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Pasteles',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sabor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='personas',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('CC', 'Centimetro cubico')], default='GR', max_length=2),
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Stock'),
        ),
        migrations.AddField(
            model_name='capapastel',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='core.Material'),
        ),
        migrations.AddField(
            model_name='capapastel',
            name='pastel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='cantreceta',
            name='ingrediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Material'),
        ),
        migrations.AddField(
            model_name='basepastel',
            name='receta',
            field=models.ManyToManyField(blank=True, to='core.CantReceta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='base',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BasePastel'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='capas',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CapaPastel'),
        ),
    ]
