# Generated by Django 2.0.6 on 2018-06-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180621_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='userprofile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PerfilUsuario'),
        ),
    ]
