# Generated by Django 2.0.6 on 2018-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180626_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cover',
            field=models.CharField(choices=[('FT', 'Fondant'), ('CR', 'Crema'), ('CH', 'Chocolate'), ('MR', 'Mermelada')], default='CR', max_length=2),
        ),
    ]
