# Generated by Django 2.0.6 on 2018-06-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='stock',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Stock'),
        ),
    ]
