# Generated by Django 2.0.6 on 2018-06-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_material_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantreceta',
            name='medida',
        ),
    ]
