# Generated by Django 2.0.6 on 2018-06-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cantreceta_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastel',
            name='personas',
            field=models.IntegerField(default=20),
        ),
    ]
